<?php
/** op-unit-model:/template/ci.phtml
 *
 * @created   2024-03-02
 * @version   1.0
 * @package   op-unit-model
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** Declare strict
 *
 */
declare(strict_types=1);

/** namespace
 *
 */
namespace OP\UNIT\MODEL;

/** Used class.
 *
 */

/* @var $args array */
echo $args['arg1'];
echo $args['arg2'];
